# Generated by Django 5.2.13 on 2026-04-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChurnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(max_length=20)),
                ('Age', models.IntegerField()),
                ('MembershipType', models.CharField(max_length=30)),
                ('PreferredCategory', models.CharField(max_length=50)),
                ('TotalOrders', models.IntegerField()),
                ('TotalSpent', models.FloatField()),
                ('LastPurchaseDaysAgo', models.IntegerField()),
                ('PurchaseFrequencyPerMonth', models.FloatField()),
                ('AppLoginFrequency', models.IntegerField()),
                ('CouponUsageCount', models.IntegerField()),
                ('ReturnCount', models.IntegerField()),
                ('SatisfactionScore', models.FloatField()),
            ],
        ),
    ]
